# Write your MySQL query statement below

SELECT EMPLOYEE_ID, NAME, COUNT(reports_count) AS reports_count, ROUND(AVG(average_age)) AS average_age
FROM
(SELECT E1.EMPLOYEE_ID, E1.NAME, E2.REPORTS_TO AS reports_count, E2.AGE AS average_age
FROM EMPLOYEES E1
JOIN EMPLOYEES E2
ON E1.EMPLOYEE_ID = E2.REPORTS_TO
GROUP BY E2.EMPLOYEE_ID, NAME)A
GROUP BY EMPLOYEE_ID, NAME
ORDER BY EMPLOYEE_ID
