# Write your MySQL query statement below

SELECT PRODUCT_NAME AS product_name, TOTAL_UNITS AS unit
FROM
(SELECT PRODUCT_NAME, SUM(UNIT) AS TOTAL_UNITS
FROM PRODUCTS P
JOIN ORDERS O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE MONTH(ORDER_DATE) = '02' AND YEAR(ORDER_DATE) = 2020
GROUP BY PRODUCT_NAME)A
WHERE TOTAL_UNITS >= 100
