# Write your MySQL query statement below

SELECT PLAYER_ID, EVENT_DATE AS FIRST_LOGIN
FROM
(SELECT PLAYER_ID, EVENT_DATE, ROW_NUMBER() OVER (PARTITION BY PLAYER_ID ORDER BY EVENT_DATE) AS RW
FROM ACTIVITY)A
WHERE RW = 1
