# Write your MySQL query statement below

#SELECT CUSTOMER_NUMBER
#FROM
#(SELECT CUSTOMER_NUMBER, ORDERS_COUNT, ROW_NUMBER() OVER (ORDER BY #ORDERS_COUNT DESC) AS RW
#FROM
#(SELECT CUSTOMER_NUMBER, COUNT(CUSTOMER_NUMBER) AS ORDERS_COUNT
#FROM ORDERS)A)B
#WHERE RW = 1

SELECT CUSTOMER_NUMBER
FROM
(SELECT CUSTOMER_NUMBER, ORDERS_COUNT, ROW_NUMBER() OVER (ORDER BY ORDERS_COUNT DESC) AS RW
FROM
(SELECT CUSTOMER_NUMBER, COUNT(CUSTOMER_NUMBER) AS ORDERS_COUNT
FROM ORDERS
GROUP BY CUSTOMER_NUMBER)A)B
WHERE RW = 1