# Write your MySQL query statement below
WITH TB1 AS(
SELECT SELL_DATE, COUNT(DISTINCT PRODUCT) AS num_sold 
FROM ACTIVITIES
GROUP BY SELL_DATE),

TB2 AS(
SELECT SELL_DATE, GROUP_CONCAT(DISTINCT PRODUCT SEPARATOR ',') AS products  
FROM Activities
GROUP BY SELL_DATE)

SELECT TB1.SELL_DATE, num_sold, products 
FROM TB1
JOIN TB2 
ON TB1.SELL_DATE = TB2.SELL_DATE 
