# Write your MySQL query statement below

WITH TB1 AS(
SELECT ACCOUNT, AMOUNT, SUM(AMOUNT) AS BALANCE
FROM TRANSACTIONS
GROUP BY ACCOUNT)

SELECT NAME, BALANCE
FROM USERS
JOIN TB1
ON USERS.ACCOUNT = TB1.account
WHERE BALANCE > 10000
