# Write your MySQL query statement below

(SELECT EMPLOYEE.EMPLOYEE_ID, DEPARTMENT_ID
FROM EMPLOYEE
JOIN
(SELECT EMPLOYEE_ID
FROM
(SELECT EMPLOYEE_ID, COUNT(DEPARTMENT_ID) AS CNT
FROM EMPLOYEE 
GROUP BY EMPLOYEE_ID)A
WHERE CNT = 1)B
ON EMPLOYEE.EMPLOYEE_ID = B.EMPLOYEE_ID)
UNION
(SELECT EMPLOYEE_ID, DEPARTMENT_ID
FROM EMPLOYEE
WHERE PRIMARY_FLAG = 'Y')






