# Write your MySQL query statement below

WITH TB1 AS(
    SELECT MACHINE_ID, PROCESS_ID, TIMESTAMP AS START
    FROM ACTIVITY
    WHERE ACTIVITY_TYPE = "start"
),

TB2 AS(
    SELECT MACHINE_ID, PROCESS_ID, TIMESTAMP AS END
    FROM ACTIVITY
    WHERE ACTIVITY_TYPE = "end"
)


SELECT MACHINE_ID, ROUND(AVG(PROCESSING_TIME),3) AS processing_time
FROM
(SELECT TB1.MACHINE_ID, TB1.PROCESS_ID, ROUND(END - START,3) AS processing_time 
FROM TB1
JOIN TB2 
ON TB1.MACHINE_ID = TB2.MACHINE_ID
AND TB1.PROCESS_ID = TB2.PROCESS_ID)A
GROUP BY MACHINE_ID
