# Write your MySQL query statement below

WITH TB1 AS(
SELECT VISIT_ID
FROM VISITS
WHERE VISIT_ID NOT IN (SELECT VISIT_ID FROM TRANSACTIONS))

SELECT CUSTOMER_ID, COUNT(CUSTOMER_ID) AS count_no_trans
FROM VISITS
JOIN TB1 
ON VISITS.VISIT_ID = TB1.VISIT_ID
GROUP BY CUSTOMER_ID

