
SELECT user_id, last_stamp
FROM
(SELECT USER_ID AS user_id, TIME_STAMP AS last_stamp , ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY TIME_STAMP DESC) AS RW
FROM LOGINS
WHERE YEAR(TIME_STAMP) = 2020)A
WHERE RW = 1
ORDER BY last_stamp DESC